universe                = docker
docker_image            = gcr.io/quantum-builds/github.com/quantumlib/jupyter_qsim:latest
arguments               = python3 test_output.py
should_transfer_files   = YES
transfer_input_files    = test_output.py
when_to_transfer_output = ON_EXIT
transfer_output_files   = dummy_output.npy
output                  = out/out.$(Cluster)-$(Process)
error                   = out/err.$(Cluster)-$(Process)
log                     = out/log.$(Cluster)-$(Process)
request_memory          = 10GB
queue 1